### ISSUE TITLE
Correct Hourly generation per group

### ISSUE THREAD

**Issue by IngridJSJ** [TradeRES/toolbox-amiris-emlab#24]
Residual load is wrong because in some years it is higher than the load. 
![image](https://user-images.githubusercontent.com/47012366/203063594-0e461f29-ef9e-4ced-90fe-8e20539d6517.png)

Also the hourly generation per group seem to be wrong: Conventionals are capped to 2906 and minimum RES generation is the same
![image](https://user-images.githubusercontent.com/47012366/203065726-bd605324-cd5a-4ffb-a411-e0c6f583617a.png)

Could you please check this?

**Comment by dlr-jk** [comment]
Yes, I'll dig into the calculations.

**Comment by dlr-jk** [comment]
Hello, @IngridJSJ:

So far, I checked the residual load calculation. It is correct since I was able to exactly replicate the values for the example that is tracked based on the input data.

Here is how it is calculated:
* Take the planned load (column "RequestedEnergyInMWH") of the DemandTrader agent.
* Calculate the fluctuating renewable generation (i.e. values of the column "AwardedPowerInMWH" grouped by timestep) for the VariableRenewableOperator agent.
  * These values do only comprise fluctuating RES, i.e. PV, windonshore, windoffshore and run of river as long as there is no "otherres" defined. If you want to include that, please let me know. Then we'd have to explicitly exclude that values.
  * Biogas is not included since it is a controllable RES source.
  * The values of the "AwardedPowerInMWH" column are the same as the feed-in potential in case there are no curtailments, hence in case prices don't drop below the marginal costs (which are assumed to be zero in the tracked example).
  * Since there is no curtailment for the trcked example, I used the input data to replicate overall RES generation and residual load. The values match exactly.

To be honest, I don't know where the increased values in your plot comes from. Do you display the correct thing here?
As of now, the load timeseries used for AMIRIS is hard-coded and not taken from the excel sheet.

There are two explanations for an increase in residual load:
* Demand is increased above the given level, i.e. the (planned) demand series is exchanged by another one.
* Renewable infeed is negative - which is not an option for AMIRIS as it is capped at 0.

The only other explanation is that the residual load plot above uses erroneous information that is not really reflecting the model inputs. Anyways, I hope that helps. I'll dig into the generation outcomes now.

**Comment by dlr-jk** [comment]
I'm sorry, I found a tiny bug for the conventionals which led to using the wrong data in the assessment. I fixed it and will add it in a dedicated issue and pull request and close this one.
